### ISSUE TITLE
Prevent hamburger menu when not needed

### ISSUE THREAD

**Issue by probonopd** [srevinsaju/get-appimage#1]
Please prevent the hamburger menu from appearing when there is actually plenty of white space in which the menu entries could be shown:

__Bad:__

![image](https://user-images.githubusercontent.com/2480569/90331013-041d9e00-dfa1-11ea-8deb-9f5d30fbab65.png)

__Good:__

![image](https://user-images.githubusercontent.com/2480569/90331033-36c79680-dfa1-11ea-8148-08a427e6a823.png)

GitHub itself has the exact same issue and it's been driving me nuts for ages ;-/

**Comment by srevinsaju** [comment]
@probonopd Can you test out the latest website?, If possible IRC

**Comment by probonopd** [comment]
Thanks @srevinsaju it's fixed now :+1:
